[project]
name = "electric"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.4.4",
    "pandas>=2.3.1",
    "pdfplumber>=0.11.7",
    "streamlit>=1.48.0",
]
